openapi: 3.0.3
info:
  title: GreetingAPI
  description: GreetingAPI
  version: 1.0.0
servers:
  - url: 'http://localhost:8080'
paths:
  /:
    get:
      summary: get greeted
      security: [ ]
      responses:
        200:
          content:
            text/plain:

