openapi: 3.0.3
info:
  title: Jokr API
  description: a simple REST API for jokes
  version: 1.0.0
servers:
  - url: 'http://localhost:8080'
paths:
  /joke:
    get:
      summary: display a random joke to the user
      security: [] # none means we'll allow anonymous access to this resource
      responses:
        200:
          description: display a random joke in plain text
          content:
            text/plain:
              schema:
                type: string
    post:
      summary: create and save a new joke
      security: []
      requestBody:
        content:
          text/plain:
            schema:
              type: string
      responses:
        201:
          description: the new joke submission was saved
          content:
            text/plain:
              schema:
                type: string
